# Autogenerated wrapper script for msgpack_cxx_jll for any
export msgpack_hpp

using boost_jll
JLLWrappers.@generate_wrapper_header("msgpack_cxx")
JLLWrappers.@declare_file_product(msgpack_hpp)
function __init__()
    JLLWrappers.@generate_init_header(boost_jll)
    JLLWrappers.@init_file_product(
        msgpack_hpp,
        "include/msgpack.hpp",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
